language: python
sudo: false
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
- unzip -q google_appengine_1.9.27.zip
install:
- pip install --upgrade pip
- pip install tox
script:
- tox
env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=coveralls-py2
  - TOXENV=coveralls-py3
  - TOXENV=py27 APPENGINE_RUNTIME=python27
  global:
  - secure: S/H779PQk4yKOmP3HbcsrdJjls5cDQDekYhvW0nvlsSkw7L+nqEhV92Lk+JMIPOYeug66NmBSqCIhLC6NHp6TK3Z6y7wNO1JeVdtl+X7b7acRNAkMz9GqkZgLP05LyB1kGUpKfzEejxvKcKQ4iAkEVVu4N5IXcO92Y/IIMuKOe4=
  - secure: Xtw10xjgdPiWrG6BZ+2B1UlkCBEtpVoHwttXj1nmroWqpIGOLDiAHVxgORe+mt4lIvDe2+cWJRRIeuY8f1xkbkR/FjNMf7iGbNJiARvcUe3ivX29cwOCyghN7IliyikHLwhntQcx2UFBDlMyYH5DqZYVzo22IyUFmPBMS58WqO4=
  - secure: kYYWxHjBauDp0b5Kt+VBzTVCYYAUrVzT+V7uQ8P6tIX3XNd96WDjGm2UzpxpmuOklyA+nuqiq6i9ukYjF31aHzce9JJVQMb7qeOZBjQMrPqKrvDaeiWItxx82CsugMRPs4DPCA28r63a3VLltv8Sd+KXtezRMhWKaimqM0ntRauP5qXUKORugkGUkS++3IxoxwVc7XkBlsRxRfCnRKcmL0fnoQDXdoZpEbwaPpQPSQwl1rd1ulCKUFYX6XGqyCeeC3qlsxnxvRy6n3yHaUv+JlMRy1+jgz/ZlzWb0vCKwUs3Jq/peZq+krfR3Ou2NujnsRHId6uo6L4mMJy1rmdk4k/ul2paPfgWNG0vhaEn4YvnBDLYVCDmuHsVTRLXnCEHwcgSI9gAzjkQaxx0gkE1abtcHqy7AMbrmNQkkXXDC+CBtBrUwiYSLo0OjobYHQHjcvmq1ALrxZto4W1npAyux2ylQlyVvSl7IU+tizHYPkkYG6fgehS/HV3s9L4ZX1uRzv4msc5/+KWimSAHfcdjs+G1hZTPVkjcQe0EFJ8kLaEv7lZlx4inJS5mzzZQaoLD3IGBTs7oTOC39yt18cuhCESXT8OhMYXHBvgvrNJPkJHgH6L8CywkxnHUER8y6GaL9DFYAQWFKgkXyTrnZBwAD7nd75bi39LyN+HXFdLqK+o=
  - secure: gxBlDnIwA1wDJhpyW3FcGfjlWh+2oc6XY289swLSKe/9CXXBwhEhGF0K3wZpJFCijXy+C1VJZO24vITqSl7kOB0vc0b4OgQIUSd36eRLsQH+bdgTQx3wldCtg1UgxYf+PwGnSL5pbDUlh0QgTtNH0BPcdzddUBspLp63JMWKNldfYDZizcQUgLy8aOAP3RQCwMSfejZbEgQEHjhV7BJFjeEJ56GUrfyWY7qkvuD8ZuudKpMV1ChFJzVCKSqK6szPM4886WmIU/FIWSLR82X5tepzQjkl3DmVdQfU230yLpkyx4nsMdrdusO2WFQ6ZGk5MeDTQk3Ws5IqhoQn1npYPM0G+lNTWcJ2sDzs6BfsxDeWE9raVl8DiT6uyXasIUEl3RBsPi6nR41oh7V1FefLj9VY6R9dr8wLXuJwI5iiTfSe7cqI+jMRnK+31CTF+/XOz+7cmMfebO8yvqLUyQc9tIA58m1OLHGxiH9UpKy/ZipDHPp3+0FeiuRfinBD17pI8XTJ/s5L+PW6cIuCex4Cm3IwMcnZrMVaf5U82///7P6I89KVRNXzlVo0ZnsGkIkL3QV7yrHC51F6/MZhJyNIRa6MHeivHhp0cKBStezTS44xpDGycly8F4CGnmsE8g5FlysWHRqHhHxNVSqfymk5+QFQ7l0o1QxzTIwifaYiMbA=
